[camera.Transform3D]
position = [-1.0, 0.0, 0.0]
[camera.CameraComponent]
farPlane = 100.0
[camera.FlyingMovement]

[cube.Transform3D]
position = [5.0, 0.0, 0.0]
[cube.MeshComponent]
mesh = "cube"
texture = "diamond_ore"
[cube.Spin]

[floor.Transform3D]
position = [0.0, 0.0, -5.0]
scale = [50.0, 50.0, 1.0]
[floor.MeshComponent]
mesh = "cube"

[prism.Transform3D]
position = [2.5, 1.0, 0.0]
parent = "camera"
[prism.MeshComponent]
mesh = "prism"
color = [0.8, 0.0, 0.0]

[mainLight.Transform3D]
rotation = [0.0, 30.0, 30.0]
[mainLight.DirLight]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]